In [1]:
import torch
from torch import nn
import numpy as np
torch.manual_seed(1)

print(torch.__version__)
torch.set_default_tensor_type('torch.FloatTensor')

1.4.0


# 模型

$y = w_0 + w_1 \cdot x_1 + w_2 \cdot x_2$

# 损失函数

$L(\mathbf{w}, b) =\frac{1}{n}\sum_{i=1}^n l^{(i)}(\mathbf{w}, b) =\frac{1}{n} \sum_{i=1}^n \frac{1}{2}\left(\mathbf{w}^\top \mathbf{x}^{(i)} + b - y^{(i)}\right)^2.$

# 优化算法

小批量随机梯度下降

- 学习率：优化的步长
- 批量大小



# 从零开始实现

# 用Pytorch实现

In [0]:
net = nn.Linear(8, 1)
x = np.arange(1,9).reshape(1,-1).astype('float32')
x = torch.from_numpy(x)

In [0]:
y = net(x)

In [10]:
print(y.shape)

torch.Size([1, 1])


In [14]:
net.weight.shape, net.bias.shape

(torch.Size([1, 8]), torch.Size([1]))

In [0]:
def square_loss(y, y_hat):
    return np.mean((y_hat-y.reshape(y_hat.shape[0]))**2)

In [21]:
y = np.array([3.14,0.98,1.32])
y_hat = np.array([2.33,1.07,1.23])
square_loss(y, y_hat)/2

0.11205000000000002

In [0]:
x = torch.rand((2,3))

In [23]:
x.shape

torch.Size([2, 3])

In [24]:
x.view((1,6))

tensor([[0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885]])

In [25]:
x.view(-1)

tensor([0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885])

In [26]:
x = torch.arange(3)
y = torch.arange(3).view(3,1)
print(x, y)

tensor([0, 1, 2]) tensor([[0],
        [1],
        [2]])
